version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: postgres_clrty_forms
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
      POSTGRES_DB: clrty-forms
      PGDATA: "/data/postgres"
    expose:
      - 5432
    volumes:
      - ./data/postgres:/var/lib/postgresql_clrty/data
