// login page
import type { NextPage } from "next";
import { useSession, signOut, getSession } from "next-auth/react";
import Head from "next/head";
import LoginForm from "../components/Auth/LoginForm";
import { trpc } from "../utils/trpc";

const Login: NextPage = () => {
  const { data: session } = useSession();
  console.log({ session });
  return (
    <>
      <Head>
        <title>CLRTY Template App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <LoginForm />
    </>
  );
};

export async function getServerSideProps(context: any) {
  const session = await getSession(context);

  if (session) {
    return {
      redirect: {
        destination: "/",
        permanent: false,
      },
    };
  }

  return {
    props: { session },
  };
}

export default Login;
