import type { NextPage } from "next";
import Head from "next/head";
import { trpc } from "../../utils/trpc";
import { DndContext } from "@dnd-kit/core";
import { Draggable } from "../../components/Form/Dragabble";
import { useState } from "react";
import { Droppable } from "../../components/Form/Droppable";
import Main from "../../components/UI/Layout/Main";

const Form: NextPage = () => {
  const [isDropped, setIsDropped] = useState(false);
  const hello = trpc.example.hello.useQuery({ text: "from tRPC" });

  const handleDragEnd = (event) => {
    if (event.over && event.over.id === "droppable") {
      setIsDropped(true);
    }
  };

  return (
    <>
      <Head>
        <title>Clrty Edit Form</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main>
      <div className="flex">
        <DndContext onDragEnd={handleDragEnd}>
          <div className="w-96 flex-none">
            {!isDropped ? <Draggable>Drag Me</Draggable> : null}
          </div>
          <div className="flex-1">
            <Droppable className="h-full rounded-lg border-2 border-dashed border-gray-200">
              {isDropped ? <Draggable>Drag Me</Draggable> : "Drop Here"}
            </Droppable>
          </div>
        </DndContext>
      </div>
      </Main>
    </>
  );
};

export default Form;
